### ISSUE TITLE
Failure to run on Windows and Linux

### ISSUE THREAD

**Issue by vaczubatiuk** [deepratna-awale/AutoExpress#10]
When i follow the instructions to the letter for both Windows and Linux, I get the same error:
Error: While importing 'autoexpress', an ImportError was raised:

Traceback (most recent call last):
  File "/home/smashlootrepeat/AI/AutoExpress/my_env/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/home/smashlootrepeat/AI/AutoExpress/autoexpress/__init__.py", line 10, in <module>
    from autoexpress.views import autoexpress
  File "/home/smashlootrepeat/AI/AutoExpress/autoexpress/views.py", line 7, in <module>
    from autoexpress.modules import (
  File "/home/smashlootrepeat/AI/AutoExpress/autoexpress/modules/image_parser.py", line 2, in <module>
    from sd_parsers import ParserManager
ModuleNotFoundError: No module named 'sd_parsers'

I manually install sd_parsers to my venv and get:
Error: While importing 'autoexpress', an ImportError was raised:

Traceback (most recent call last):
  File "/home/smashlootrepeat/AI/AutoExpress/my_env/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/home/smashlootrepeat/AI/AutoExpress/autoexpress/__init__.py", line 10, in <module>
    from autoexpress.views import autoexpress
  File "/home/smashlootrepeat/AI/AutoExpress/autoexpress/views.py", line 7, in <module>
    from autoexpress.modules import (
  File "/home/smashlootrepeat/AI/AutoExpress/autoexpress/modules/image_parser.py", line 3, in <module>
    from sd_parsers import Generators
ImportError: cannot import name 'Generators' from 'sd_parsers' (/home/smashlootrepeat/AI/AutoExpress/my_env/lib/python3.12/site-packages/sd_parsers/__init__.py)

**Comment by vaczubatiuk** [comment]
Fixed it, changed Line 2 in modules/image_parser.py to: from sd_parsers.data import Generators

**Comment by deepratna-awale** [comment]
Changed the image parser module as per the suggestion. Thanks!
